# -*- coding: utf-8 -*-
"""Assignment- Coding Loops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RGJDzZk32yCfVGlZI3p5SZZF-Pn5kL9Z
"""

def fibonacci(limit):
  fib_sequence=[0,1]
  while fib_sequence[-1]+fib_sequence[-2]<=limit:
    fib_sequence.append(fib_sequence[-1]+fib_sequence[-2])
  return fib_sequence

limit=int(input("Enter the limit for Fibonacci numbers:"))
fib_numbers=fibonacci(limit)
print("Fibonacci numbers up to",limit,"are:",fib_numbers)