# -*- coding: utf-8 -*-
"""Working with Data Structures in Python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJPgq1ZaLzRZlT-fd9KtUoxSRhI4c5Dq
"""

E={0,2,4,6,8}
N={1,2,3,4,5}

#Union
union_set=E.union(N)
print("Union of E and N is",union_set)

#Intersection
intersection_set=E.intersection(N)
print("Intersection of E and N is", intersection_set)

#Difference
difference_set=E.difference(N)
print("Difference of E and N is",difference_set)

#Symmetric difference
symmetric_difference_set=E.symmetric_difference(N)
print("Symmetric difference of E and N is",symmetric_difference_set)